name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build the Application
        run: npm run build

      - name: Archive Build Artifacts
        run: |
          zip -r build.zip dist/
          ls -lh build.zip

      - name: Deploy to EC2 via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          echo "Creating remote app directory..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$SSH_HOST "mkdir -p /home/$SSH_USER/product-naga"

          echo "Copying build files..."
          scp -o StrictHostKeyChecking=no -i private_key.pem -r dist package*.json $SSH_USER@$SSH_HOST:/home/$SSH_USER/product-naga/
          #run
          echo "Running deployment commands on EC2..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SSH_USER@$SSH_HOST << EOF
            cd /home/$SSH_USER/product-naga
            npm install pm2 -g
            pm2 delete product-naga || true
            pm2 start dist/src/main.js --name product-naga
          EOF
